# netlify.toml  ── final, working version
[build]
command        = "npm run build"
publish        = "package/storefront-spiceleaf/dist"
edge_functions = "netlify/edge-functions"

[[edge_functions]]
function = "entry.netlify-edge"
path     = "/*"

[[headers]]
  # Cache GET requests for 2 minutes (120 seconds)
  for = "/*"
    [headers.values]
    Cache-Control = "public, max-age=120"
