name: Build & Deploy Content Fashion

on:
  push:
    paths:
      - 'package/content-fashion/**'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./package/content-fashion
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/content-fashion:latest

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository_owner }}/content-fashion:latest
            docker stop content-fashion || true
            docker rm content-fashion || true
            docker run -d --name content-fashion -p 80:80 ghcr.io/${{ github.repository_owner }}/content-fashion:latest
